# SPDX-FileCopyrightText: Copyright (c) 2019-2025 Aibolit
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".latexmkrc",
    "**.zip",
    "**.jar",
    "aibolit/binary_files/model.pkl",
    ".dcignore",
    "MANIFEST.in",
    "**.class",
    "**.puml",
    "test/stats/model.pkl",
    ".pdd",
    "**.csv",
    "**.jpg",
    "**.json",
    "**.md",
    "**.png",
    "**.svg",
    "**.txt",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.latexmkrc",
    "**/.pdd",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/CNAME",
    "**/Gemfile.lock",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2019-2025 Aibolit"
SPDX-License-Identifier = "MIT"
